# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: trzsz.lrzsz
PackageVersion: 0.12.21rc
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: lrzsz_0.12.21rc_windows_x86_64\rz.exe
  PortableCommandAlias: rz
- RelativeFilePath: lrzsz_0.12.21rc_windows_x86_64\sz.exe
  PortableCommandAlias: sz
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/trzsz/lrzsz-win32/releases/download/v0.12.21rc/lrzsz_0.12.21rc_windows_x86_64.zip
  InstallerSha256: DACE2DB172B1B5A1E5998692760A75355B254E1826718D88BAE7FA3A6DE3C325
ManifestType: installer
ManifestVersion: 1.5.0
